url: https://fusionevents.github.io
baseurl: 

# Site settings
title: Fusion
email: fusioneventsplanners@gmail.com
description: "We designs beyond your dreams"


# Team names, titles and social links
people:
- name: Siju Sam Thomas
  pic: 1
  position: Event Co-ordinator
  social:
    - title: whatsapp
      url: https://api.whatsapp.com/send?phone=+919995339485
    - title: facebook
      url: https://www.facebook.com/sijuoo7
    - title: phone 
      url: tel:+919995339485
      
- name: Sajil
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Anil
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ARUNKSOMAN2
  - title: facebook
    url: https://www.facebook.com/groups/845876295565560/
  - title: whatsapp
    url: https://api.whatsapp.com/send?phone=+919995339485
  - title: phone
    url: tel:+919995339485
  - title: envelope
    url: mailto:fusioneventsplanners@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
